### ISSUE TITLE
Problem in installing bahmni for production on ubuntu 14.04

### ISSUE THREAD

**Issue by ahmedkhak** [Bahmni/default-config#1]
I am trying to install bahmni for development on my ubuntu 14.04 server. I am following instruction for installation which are mentioned on that page https://bahmni.atlassian.net/wiki/display/BAH/Bahmni+Using+Docker, and following instruction under that heading "Configuring Bahmni For Development". I did these steps

step 1: I created a directory named "bahmni-code-dev"
step 2: I clone these repositiories in "bahmni-code-dev" directory

'default-config - https://github.com/Bhamni/default-config.git
openmrs-distro-bahmni - https://github.com/Bhamni/openmrs-distro-bahmni
openmrs-module-bahmniapps - https://github.com/Bhamni/openmrs-module-bahmniapps'

Step 3: I build the project by that command "mvn clean install"
step 4: id did "cd openmrs-module-bahmniapps/ui"
step 5: then i did 

'npm install -g bower 
npm install -g grunt-cli 
gem install compass'

step 6: i did "npm install"
step 7: then i did "bower install"
step 8: then i did "grunt", (grunt shows success message at the end)

Now i am not clear with points which are mentioned under heading "Building bahmni-core". Is it really necessary to build "bahmni-core" for developement. 

Please guide me how can i change ports and where to locate files for that

Thank you

**Comment by rnjn** [comment]
Hi,

Please look at out wiki for installation/setup. 
You can raise your questions on IRC - freenode - #bahmni

I am closing this issue now since it has no direct bearing on default configuration.
