### ISSUE TITLE
Reports default SQL location needs to be updated.

### ISSUE THREAD

**Issue by annooritdept** [Bahmni/default-config#110]
When running with default config, the bahmni-reports container loads up the config (including SQL reports) under `/etc` instead of `/var/www`

As such the sqlPath for those reports that use it in the `openmrs/apps/reports/reports.json` should probably be updated to start with `/etc` instead of `/var/www`.

Let me know if this is already fixed, and I'm just using the wrong branch. 

In case anyone else runs into this error, this is what I got when trying to run the 'Generic Laboratory Services' report:
I encountered a "500 Internal Server Error" in my browser, and the following StackTrace in my docker logs
```
bahmni-standard-reports-1                | java.lang.NullPointerException
bahmni-standard-reports-1                | 	at org.antlr.runtime.ANTLRStringStream.<init>(ANTLRStringStream.java:75)
bahmni-standard-reports-1                | 	at org.stringtemplate.v4.compiler.Compiler.compile(Compiler.java:111)
bahmni-standard-reports-1                | 	at org.stringtemplate.v4.STGroup.compile(STGroup.java:427)
bahmni-standard-reports-1                | 	at org.stringtemplate.v4.ST.<init>(ST.java:142)
bahmni-standard-reports-1                | 	at org.stringtemplate.v4.ST.<init>(ST.java:136)
bahmni-standard-reports-1                | 	at org.bahmni.reports.template.SqlReportTemplate.getSqlString(SqlReportTemplate.java:57)
bahmni-standard-reports-1                | 	at org.bahmni.reports.template.SqlReportTemplate.build(SqlReportTemplate.java:32)
bahmni-standard-reports-1                | 	at org.bahmni.reports.util.BahmniReportUtil.build(BahmniReportUtil.java:33)
bahmni-standard-reports-1                | 	at org.bahmni.reports.web.ReportGenerator.invoke(ReportGenerator.java:60)
bahmni-standard-reports-1                | 	at org.bahmni.reports.web.MainReportController.getReport(MainReportController.java:68)
```

until I updated the location of the file manually in the reports.json file to be `/etc/bahmni_config/openmrs/apps/reports/sql/testCount.sql`.

Let me know if there's any other info you need, or if I should try and fork and do a pull request if that would be most helpful.

**Comment by gsluthra** [comment]
Thanks for pointing this out. Can you please open an issue in Bahmni JIRA. We don't track Bahmni issues in Github. Here is an example ticket: https://bahmni.atlassian.net/browse/BAH-3074, similar to what you encountered.

Also, if you can raise a PR for the fix, which will likely be in bahmni-reports, that would be really appreciated! thanks @annooritdept 

cc: @rahu1ramesh @mohan-13
